language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r src/requirements.txt
  - pip install -r src/tests/requirements.txt
# command to run tests
script:
  - pytest

after_success:
  - pylint --disable=fixme src/app
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml